// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("Usage", "xUnit1045:Avoid using TheoryData type arguments that might not be serializable", Justification = "<Pending>", Scope = "member", Target = "~M:Respira.Application.Test.Features.Shared.ManageRange.RangeValidatorTest.Validate_ValidRange_Success(Respira.Clinical.Domain.Models.Range)")]
[assembly: SuppressMessage("Usage", "xUnit1045:Avoid using TheoryData type arguments that might not be serializable", Justification = "<Pending>", Scope = "member", Target = "~M:Respira.Application.Test.Features.ClinicalVariables.CreateClinicalVariable.CreateClinicalVariableHandlerTest.CreateClinicalVariable_NormalRangeOutsideAcceptedRange_Fail(Respira.Clinical.Domain.Models.Range,Respira.Clinical.Domain.Models.Range)~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Usage", "xUnit1045:Avoid using TheoryData type arguments that might not be serializable", Justification = "<Pending>", Scope = "member", Target = "~M:Respira.Application.Test.Features.ClinicalVariables.CreateClinicalVariable.CreateClinicalVariableHandlerTest.CreateClinicalVariable_NormalRangeWithinAcceptedRange_Success(Respira.Clinical.Domain.Models.Range,Respira.Clinical.Domain.Models.Range)~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Usage", "xUnit1045:Avoid using TheoryData type arguments that might not be serializable", Justification = "<Pending>", Scope = "member", Target = "~M:Respira.Application.Test.Features.ClinicalVariables.UpdateClinicalVariable.UpdateClinicalVariableHandlerTest.UpdateClinicalVariable_NormalRangeOutsideAcceptedRange_Fail(Respira.Clinical.Domain.Models.Range,Respira.Clinical.Domain.Models.Range)~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Usage", "xUnit1045:Avoid using TheoryData type arguments that might not be serializable", Justification = "<Pending>", Scope = "member", Target = "~M:Respira.Application.Test.Features.ClinicalVariables.UpdateClinicalVariable.UpdateClinicalVariableHandlerTest.UpdateClinicalVariable_NormalRangeWithinAcceptedRange_Success(Respira.Clinical.Domain.Models.Range,Respira.Clinical.Domain.Models.Range)~System.Threading.Tasks.Task")]
