// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Respira.Clinical.Infrastructure.Data;

#nullable disable

namespace Respira.Clinical.Infrastructure.Migrations
{
    [DbContext(typeof(ClinicalDbContext))]
    [Migration("20261006091056_Clinical_migrations_v10_category_as_str_cli_var")]
    partial class Clinical_migrations_v10_category_as_str_cli_var
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AntibioticMedicineComposition", b =>
                {
                    b.Property<Guid>("AntibioticsId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("MedicineCompositionId")
                        .HasColumnType("uuid");

                    b.HasKey("AntibioticsId", "MedicineCompositionId");

                    b.HasIndex("MedicineCompositionId");

                    b.ToTable("medicine_composition_antibiotics", (string)null);
                });

            modelBuilder.Entity("CriterionTreatment", b =>
                {
                    b.Property<Guid>("CriteriaId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TreatmentId")
                        .HasColumnType("uuid");

                    b.HasKey("CriteriaId", "TreatmentId");

                    b.HasIndex("TreatmentId");

                    b.ToTable("treatment_criteria", (string)null);
                });

            modelBuilder.Entity("PathogenTreatment", b =>
                {
                    b.Property<Guid>("PathogensId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TreatmentId")
                        .HasColumnType("uuid");

                    b.HasKey("PathogensId", "TreatmentId");

                    b.HasIndex("TreatmentId");

                    b.ToTable("treatment_pathogens", (string)null);
                });

            modelBuilder.Entity("Respira.Clinical.Domain.Entities.Antibiotic", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AntibioticGroupId")
                        .HasColumnType("uuid");

                    b.Property<string>("Classification")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AntibioticGroupId");

                    b.HasIndex("Name", "Classification");

                    b.ToTable("antibiotics", (string)null);
                });

            modelBuilder.Entity("Respira.Clinical.Domain.Entities.AntibioticGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.HasIndex("ParentId");

                    b.ToTable("antibiotic_groups", (string)null);
                });

            modelBuilder.Entity("Respira.Clinical.Domain.Entities.ClinicalMetrics", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("clinical_metrics", (string)null);
                });

            modelBuilder.Entity("Respira.Clinical.Domain.Entities.ClinicalVariable", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CanonicalUnit")
                        .HasColumnType("text");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Prerequisite")
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("value_type")
                        .IsRequired()
                        .HasMaxLength(34)
                        .HasColumnType("character varying(34)");

                    b.HasKey("Id");

                    b.ToTable("clinical_variables", (string)null);

                    b.HasDiscriminator<string>("value_type").HasValue("ClinicalVariable");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Respira.Clinical.Domain.Entities.Criterion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Formula")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("criteria", (string)null);
                });

            modelBuilder.Entity("Respira.Clinical.Domain.Entities.Dosage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AntibioticId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Dose")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("RouteOfAdministration")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AntibioticId");

                    b.ToTable("dosages", (string)null);
                });

            modelBuilder.Entity("Respira.Clinical.Domain.Entities.MedicineComposition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("TreatmentId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("TreatmentId");

                    b.ToTable("treatment_medicine_compositions", (string)null);
                });

            modelBuilder.Entity("Respira.Clinical.Domain.Entities.MetricsRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClinicalMetricsId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CriterionId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("rule_type")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("character varying(21)");

                    b.HasKey("Id");

                    b.HasIndex("ClinicalMetricsId");

                    b.HasIndex("CriterionId");

                    b.ToTable("metrics_rules", (string)null);

                    b.HasDiscriminator<string>("rule_type").HasValue("MetricsRule");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Respira.Clinical.Domain.Entities.Pathogen", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsAtypical")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("pathogens", (string)null);
                });

            modelBuilder.Entity("Respira.Clinical.Domain.Entities.RiskFactor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CriterionId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("PathogenId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CriterionId");

                    b.HasIndex("PathogenId");

                    b.ToTable("risk_factors", (string)null);
                });

            modelBuilder.Entity("Respira.Clinical.Domain.Entities.SuspectedCause", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("PathogenId")
                        .HasColumnType("uuid");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TreatmentSite")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("PathogenId");

                    b.ToTable("suspected_causes", (string)null);
                });

            modelBuilder.Entity("Respira.Clinical.Domain.Entities.Treatment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TreatmentSite")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("treatments", (string)null);
                });

            modelBuilder.Entity("Respira.Clinical.Domain.Entities.BooleanClinicalVariable", b =>
                {
                    b.HasBaseType("Respira.Clinical.Domain.Entities.ClinicalVariable");

                    b.HasDiscriminator().HasValue("boolean_clinical_variable");
                });

            modelBuilder.Entity("Respira.Clinical.Domain.Entities.CategoricalClinicalVariable", b =>
                {
                    b.HasBaseType("Respira.Clinical.Domain.Entities.ClinicalVariable");

                    b.PrimitiveCollection<List<string>>("AcceptedValues")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.HasDiscriminator().HasValue("categorical_clinical_variable");
                });

            modelBuilder.Entity("Respira.Clinical.Domain.Entities.NumericClinicalVariable", b =>
                {
                    b.HasBaseType("Respira.Clinical.Domain.Entities.ClinicalVariable");

                    b.HasDiscriminator().HasValue("numeric_clinical_variable");
                });

            modelBuilder.Entity("Respira.Clinical.Domain.Entities.MajorMinorRule", b =>
                {
                    b.HasBaseType("Respira.Clinical.Domain.Entities.MetricsRule");

                    b.Property<bool>("IsMajor")
                        .HasColumnType("boolean");

                    b.HasDiscriminator().HasValue("major_minor_rule");
                });

            modelBuilder.Entity("Respira.Clinical.Domain.Entities.ScoringRule", b =>
                {
                    b.HasBaseType("Respira.Clinical.Domain.Entities.MetricsRule");

                    b.Property<string>("ScoreFunction")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.HasDiscriminator().HasValue("scoring_rule");
                });

            modelBuilder.Entity("AntibioticMedicineComposition", b =>
                {
                    b.HasOne("Respira.Clinical.Domain.Entities.Antibiotic", null)
                        .WithMany()
                        .HasForeignKey("AntibioticsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Respira.Clinical.Domain.Entities.MedicineComposition", null)
                        .WithMany()
                        .HasForeignKey("MedicineCompositionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CriterionTreatment", b =>
                {
                    b.HasOne("Respira.Clinical.Domain.Entities.Criterion", null)
                        .WithMany()
                        .HasForeignKey("CriteriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Respira.Clinical.Domain.Entities.Treatment", null)
                        .WithMany()
                        .HasForeignKey("TreatmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PathogenTreatment", b =>
                {
                    b.HasOne("Respira.Clinical.Domain.Entities.Pathogen", null)
                        .WithMany()
                        .HasForeignKey("PathogensId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Respira.Clinical.Domain.Entities.Treatment", null)
                        .WithMany()
                        .HasForeignKey("TreatmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Respira.Clinical.Domain.Entities.Antibiotic", b =>
                {
                    b.HasOne("Respira.Clinical.Domain.Entities.AntibioticGroup", "AntibioticGroup")
                        .WithMany()
                        .HasForeignKey("AntibioticGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AntibioticGroup");
                });

            modelBuilder.Entity("Respira.Clinical.Domain.Entities.AntibioticGroup", b =>
                {
                    b.HasOne("Respira.Clinical.Domain.Entities.AntibioticGroup", "Parent")
                        .WithMany()
                        .HasForeignKey("ParentId");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("Respira.Clinical.Domain.Entities.Dosage", b =>
                {
                    b.HasOne("Respira.Clinical.Domain.Entities.Antibiotic", "Antibiotic")
                        .WithMany("Dosages")
                        .HasForeignKey("AntibioticId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Respira.Clinical.Domain.Models.Range", "Crcl", b1 =>
                        {
                            b1.Property<Guid>("DosageId");

                            b1.Property<bool>("IsMaxExclusive");

                            b1.Property<bool>("IsMinExclusive");

                            b1.Property<decimal>("Max");

                            b1.Property<decimal>("Min");

                            b1.Property<string>("Unit");

                            b1.HasKey("DosageId");

                            b1.ToTable("dosages");

                            b1
                                .ToJson("Crcl")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("DosageId");
                        });

                    b.Navigation("Antibiotic");

                    b.Navigation("Crcl");
                });

            modelBuilder.Entity("Respira.Clinical.Domain.Entities.MedicineComposition", b =>
                {
                    b.HasOne("Respira.Clinical.Domain.Entities.Treatment", "Treatment")
                        .WithMany("Medicines")
                        .HasForeignKey("TreatmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Treatment");
                });

            modelBuilder.Entity("Respira.Clinical.Domain.Entities.MetricsRule", b =>
                {
                    b.HasOne("Respira.Clinical.Domain.Entities.ClinicalMetrics", "ClinicalMetrics")
                        .WithMany("Rules")
                        .HasForeignKey("ClinicalMetricsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Respira.Clinical.Domain.Entities.Criterion", "Criterion")
                        .WithMany()
                        .HasForeignKey("CriterionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClinicalMetrics");

                    b.Navigation("Criterion");
                });

            modelBuilder.Entity("Respira.Clinical.Domain.Entities.RiskFactor", b =>
                {
                    b.HasOne("Respira.Clinical.Domain.Entities.Criterion", "Criterion")
                        .WithMany()
                        .HasForeignKey("CriterionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Respira.Clinical.Domain.Entities.Pathogen", "Pathogen")
                        .WithMany("RiskFactors")
                        .HasForeignKey("PathogenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Criterion");

                    b.Navigation("Pathogen");
                });

            modelBuilder.Entity("Respira.Clinical.Domain.Entities.SuspectedCause", b =>
                {
                    b.HasOne("Respira.Clinical.Domain.Entities.Pathogen", "Pathogen")
                        .WithMany()
                        .HasForeignKey("PathogenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pathogen");
                });

            modelBuilder.Entity("Respira.Clinical.Domain.Entities.NumericClinicalVariable", b =>
                {
                    b.OwnsOne("Respira.Clinical.Domain.Models.Range", "AcceptedRange", b1 =>
                        {
                            b1.Property<Guid>("NumericClinicalVariableId");

                            b1.Property<bool>("IsMaxExclusive");

                            b1.Property<bool>("IsMinExclusive");

                            b1.Property<decimal>("Max");

                            b1.Property<decimal>("Min");

                            b1.Property<string>("Unit");

                            b1.HasKey("NumericClinicalVariableId");

                            b1.ToTable("clinical_variables");

                            b1
                                .ToJson("AcceptedRange")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("NumericClinicalVariableId");
                        });

                    b.OwnsOne("Respira.Clinical.Domain.Models.Range", "NormalRange", b1 =>
                        {
                            b1.Property<Guid>("NumericClinicalVariableId");

                            b1.Property<bool>("IsMaxExclusive");

                            b1.Property<bool>("IsMinExclusive");

                            b1.Property<decimal>("Max");

                            b1.Property<decimal>("Min");

                            b1.Property<string>("Unit");

                            b1.HasKey("NumericClinicalVariableId");

                            b1.ToTable("clinical_variables");

                            b1
                                .ToJson("NormalRange")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("NumericClinicalVariableId");
                        });

                    b.Navigation("AcceptedRange")
                        .IsRequired();

                    b.Navigation("NormalRange");
                });

            modelBuilder.Entity("Respira.Clinical.Domain.Entities.Antibiotic", b =>
                {
                    b.Navigation("Dosages");
                });

            modelBuilder.Entity("Respira.Clinical.Domain.Entities.ClinicalMetrics", b =>
                {
                    b.Navigation("Rules");
                });

            modelBuilder.Entity("Respira.Clinical.Domain.Entities.Pathogen", b =>
                {
                    b.Navigation("RiskFactors");
                });

            modelBuilder.Entity("Respira.Clinical.Domain.Entities.Treatment", b =>
                {
                    b.Navigation("Medicines");
                });
#pragma warning restore 612, 618
        }
    }
}
