// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Respira.Clinical.Infrastructure.Data;


#nullable disable

namespace Respira.Clinical.Infrastructure.Migrations
{
    [DbContext(typeof(ClinicalDbContext))]
    [Migration("20260918020627_clinical_migrations_v2_add_antibiotics")]
    partial class Clinical_migrations_v2_add_antibiotics
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Respira.Domain.Entities.Antibiotic", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AntibioticGroupId")
                        .HasColumnType("uuid");

                    b.Property<string>("Classification")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.PrimitiveCollection<List<Guid>>("DosageIds")
                        .IsRequired()
                        .HasColumnType("uuid[]");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.PrimitiveCollection<List<Guid>>("PathogenIds")
                        .IsRequired()
                        .HasColumnType("uuid[]");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AntibioticGroupId");

                    b.HasIndex("Name", "Classification");

                    b.ToTable("antibiotics", (string)null);
                });

            modelBuilder.Entity("Respira.Domain.Entities.AntibioticGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.HasIndex("ParentId");

                    b.ToTable("antibiotic_groups", (string)null);
                });

            modelBuilder.Entity("Respira.Domain.Entities.ClinicalVariable", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CanonicalUnit")
                        .HasColumnType("text");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ValueType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("clinical_variables", (string)null);
                });

            modelBuilder.Entity("Respira.Domain.Entities.Criterion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Formula")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("criteria", (string)null);
                });

            modelBuilder.Entity("Respira.Domain.Entities.Dosage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AntibioticId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Dose")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("RouteOfAdministration")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AntibioticId");

                    b.ToTable("dosages", (string)null);
                });

            modelBuilder.Entity("Respira.Domain.Entities.Pathogen", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AntibioticId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsAtypical")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AntibioticId");

                    b.ToTable("pathogens", (string)null);
                });

            modelBuilder.Entity("Respira.Domain.Entities.RiskFactor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CriterionId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("PathogenId")
                        .HasColumnType("uuid");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CriterionId");

                    b.HasIndex("PathogenId");

                    b.ToTable("risk_factors", (string)null);
                });

            modelBuilder.Entity("Respira.Domain.Entities.ScoreMetrics", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("score_metrics", (string)null);
                });

            modelBuilder.Entity("Respira.Domain.Entities.ScoringRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CriterionId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("ScoreFunction")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<Guid>("ScoreMetricsId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CriterionId");

                    b.HasIndex("ScoreMetricsId");

                    b.ToTable("scoring_rules", (string)null);
                });

            modelBuilder.Entity("Respira.Domain.Entities.SuspectedCause", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("PathogenId")
                        .HasColumnType("uuid");

                    b.Property<int>("Severity")
                        .HasColumnType("integer");

                    b.Property<int>("TreatmentSite")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("PathogenId");

                    b.ToTable("SuspectedCauses");
                });

            modelBuilder.Entity("Respira.Domain.Entities.Antibiotic", b =>
                {
                    b.HasOne("Respira.Domain.Entities.AntibioticGroup", "AntibioticGroup")
                        .WithMany()
                        .HasForeignKey("AntibioticGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AntibioticGroup");
                });

            modelBuilder.Entity("Respira.Domain.Entities.AntibioticGroup", b =>
                {
                    b.HasOne("Respira.Domain.Entities.AntibioticGroup", "Parent")
                        .WithMany()
                        .HasForeignKey("ParentId");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("Respira.Domain.Entities.Dosage", b =>
                {
                    b.HasOne("Respira.Domain.Entities.Antibiotic", "Antibiotic")
                        .WithMany("Dosages")
                        .HasForeignKey("AntibioticId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Respira.Domain.Models.Range", "Crcl", b1 =>
                        {
                            b1.Property<Guid>("DosageId");

                            b1.Property<bool>("IsMaxExclusive");

                            b1.Property<bool>("IsMinExclusive");

                            b1.Property<decimal>("Max");

                            b1.Property<decimal>("Min");

                            b1.Property<string>("Unit");

                            b1.HasKey("DosageId");

                            b1.ToTable("dosages");

                            b1
                                .ToJson("Crcl")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("DosageId");
                        });

                    b.Navigation("Antibiotic");

                    b.Navigation("Crcl");
                });

            modelBuilder.Entity("Respira.Domain.Entities.Pathogen", b =>
                {
                    b.HasOne("Respira.Domain.Entities.Antibiotic", null)
                        .WithMany("AntibioticSpectra")
                        .HasForeignKey("AntibioticId");
                });

            modelBuilder.Entity("Respira.Domain.Entities.RiskFactor", b =>
                {
                    b.HasOne("Respira.Domain.Entities.Criterion", "Criterion")
                        .WithMany()
                        .HasForeignKey("CriterionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Respira.Domain.Entities.Pathogen", "Pathogen")
                        .WithMany("RiskFactors")
                        .HasForeignKey("PathogenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Criterion");

                    b.Navigation("Pathogen");
                });

            modelBuilder.Entity("Respira.Domain.Entities.ScoringRule", b =>
                {
                    b.HasOne("Respira.Domain.Entities.Criterion", "Criterion")
                        .WithMany()
                        .HasForeignKey("CriterionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Respira.Domain.Entities.ScoreMetrics", "ScoreMetrics")
                        .WithMany("ScoringRules")
                        .HasForeignKey("ScoreMetricsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Criterion");

                    b.Navigation("ScoreMetrics");
                });

            modelBuilder.Entity("Respira.Domain.Entities.SuspectedCause", b =>
                {
                    b.HasOne("Respira.Domain.Entities.Pathogen", "Pathogen")
                        .WithMany()
                        .HasForeignKey("PathogenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pathogen");
                });

            modelBuilder.Entity("Respira.Domain.Entities.Antibiotic", b =>
                {
                    b.Navigation("AntibioticSpectra");

                    b.Navigation("Dosages");
                });

            modelBuilder.Entity("Respira.Domain.Entities.Pathogen", b =>
                {
                    b.Navigation("RiskFactors");
                });

            modelBuilder.Entity("Respira.Domain.Entities.ScoreMetrics", b =>
                {
                    b.Navigation("ScoringRules");
                });
#pragma warning restore 612, 618
        }
    }
}
