// <auto-generated />
using System;
using System.Collections.Generic;
using Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260723022043_InitClinicalDb")]
    partial class InitClinicalDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AntibiogramAntibiotic", b =>
                {
                    b.Property<Guid>("AntibiogramId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("MicsId")
                        .HasColumnType("uuid");

                    b.HasKey("AntibiogramId", "MicsId");

                    b.HasIndex("MicsId");

                    b.ToTable("antibiogram_mic_groups", (string)null);
                });

            modelBuilder.Entity("AntibiogramAntibiotic1", b =>
                {
                    b.Property<Guid>("Antibiogram1Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("FirstPriorityMedicinesId")
                        .HasColumnType("uuid");

                    b.HasKey("Antibiogram1Id", "FirstPriorityMedicinesId");

                    b.HasIndex("FirstPriorityMedicinesId");

                    b.ToTable("antibiogram_first_priority_medicines", (string)null);
                });

            modelBuilder.Entity("AntibiogramAntibiotic2", b =>
                {
                    b.Property<Guid>("Antibiogram2Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SecondPriorityMedicinesId")
                        .HasColumnType("uuid");

                    b.HasKey("Antibiogram2Id", "SecondPriorityMedicinesId");

                    b.HasIndex("SecondPriorityMedicinesId");

                    b.ToTable("antibiogram_second_priority_medicines", (string)null);
                });

            modelBuilder.Entity("AntibioticEmpiricTreatmentProtocol", b =>
                {
                    b.Property<Guid>("EmpiricTreatmentProtocolId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("MedicinesId")
                        .HasColumnType("uuid");

                    b.HasKey("EmpiricTreatmentProtocolId", "MedicinesId");

                    b.HasIndex("MedicinesId");

                    b.ToTable("empiric_treatment_protocol_medicine", (string)null);
                });

            modelBuilder.Entity("AntibioticPathogen", b =>
                {
                    b.Property<Guid>("AntibioticSpectraId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("MedicinesId")
                        .HasColumnType("uuid");

                    b.HasKey("AntibioticSpectraId", "MedicinesId");

                    b.HasIndex("MedicinesId");

                    b.ToTable("antibiotic_pathogen", (string)null);
                });

            modelBuilder.Entity("CriterionEmpiricTreatmentProtocol", b =>
                {
                    b.Property<Guid>("EmpiricTreatmentProtocolId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OtherCriteriaId")
                        .HasColumnType("uuid");

                    b.HasKey("EmpiricTreatmentProtocolId", "OtherCriteriaId");

                    b.HasIndex("OtherCriteriaId");

                    b.ToTable("empiric_treatment_protocol_other_criteria", (string)null);
                });

            modelBuilder.Entity("Domain.Models.Antibiogram", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.PrimitiveCollection<List<Guid>>("FirstPriorityMedicineIds")
                        .IsRequired()
                        .HasColumnType("uuid[]");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.PrimitiveCollection<List<Guid>>("MicIds")
                        .IsRequired()
                        .HasColumnType("uuid[]");

                    b.Property<string>("MicLevel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("PathogenId")
                        .HasColumnType("uuid");

                    b.PrimitiveCollection<List<Guid>>("SecondPriorityMedicineIds")
                        .IsRequired()
                        .HasColumnType("uuid[]");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("PathogenId");

                    b.ToTable("antibiograms", (string)null);
                });

            modelBuilder.Entity("Domain.Models.Antibiotic", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AntibioticGroupId")
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.PrimitiveCollection<List<Guid>>("DosageIds")
                        .IsRequired()
                        .HasColumnType("uuid[]");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.PrimitiveCollection<List<Guid>>("PathogenIds")
                        .IsRequired()
                        .HasColumnType("uuid[]");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AntibioticGroupId");

                    b.HasIndex("Name", "Category");

                    b.ToTable("antibiotics", (string)null);
                });

            modelBuilder.Entity("Domain.Models.AntibioticGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.HasIndex("ParentId");

                    b.ToTable("antibiotic_groups", (string)null);
                });

            modelBuilder.Entity("Domain.Models.Cause", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DiseaseId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("PathogenId")
                        .HasColumnType("uuid");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TreatmentSite")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("DiseaseId");

                    b.HasIndex("PathogenId");

                    b.ToTable("disease_causes", (string)null);
                });

            modelBuilder.Entity("Domain.Models.Criterion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("type")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)");

                    b.HasKey("Id");

                    b.ToTable("criteria", (string)null);

                    b.HasDiscriminator<string>("type").HasValue("Criterion");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Domain.Models.Disease", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Algorithm")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("IcuScoreThreshold")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("diseases", (string)null);
                });

            modelBuilder.Entity("Domain.Models.Dosage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AntibioticId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Dose")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("RouteOfAdministration")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AntibioticId");

                    b.ToTable("dosages", (string)null);
                });

            modelBuilder.Entity("Domain.Models.EmpiricTreatmentProtocol", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DiseaseId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateOnly>("IssueDate")
                        .HasColumnType("date");

                    b.Property<string>("Issuer")
                        .IsRequired()
                        .HasColumnType("text");

                    b.PrimitiveCollection<List<Guid>>("MedicineIds")
                        .IsRequired()
                        .HasColumnType("uuid[]");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.PrimitiveCollection<List<Guid>>("OtherCriteriaIds")
                        .IsRequired()
                        .HasColumnType("uuid[]");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("SpecialInfectionId")
                        .HasColumnType("uuid");

                    b.Property<string>("TreatmentSite")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DiseaseId");

                    b.HasIndex("SpecialInfectionId");

                    b.ToTable("empiric_treatment_protocols", (string)null);
                });

            modelBuilder.Entity("Domain.Models.IcuHospitalizeCriterion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CriterionId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DiseaseId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int>("Score")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CriterionId");

                    b.HasIndex("DiseaseId");

                    b.ToTable("icu_hospitalize_criteria", (string)null);
                });

            modelBuilder.Entity("Domain.Models.Pathogen", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.PrimitiveCollection<List<Guid>>("AntibioticIds")
                        .IsRequired()
                        .HasColumnType("uuid[]");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("pathogens", (string)null);
                });

            modelBuilder.Entity("Domain.Models.ResistanceRiskFactor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CriterionId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DiseaseId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("PathogenId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CriterionId");

                    b.HasIndex("DiseaseId");

                    b.HasIndex("PathogenId");

                    b.ToTable("resistance_risk_factors", (string)null);
                });

            modelBuilder.Entity("Domain.Models.BooleanCriterion", b =>
                {
                    b.HasBaseType("Domain.Models.Criterion");

                    b.HasDiscriminator().HasValue("boolean");
                });

            modelBuilder.Entity("Domain.Models.NumericCriterion", b =>
                {
                    b.HasBaseType("Domain.Models.Criterion");

                    b.HasDiscriminator().HasValue("numeric");
                });

            modelBuilder.Entity("AntibiogramAntibiotic", b =>
                {
                    b.HasOne("Domain.Models.Antibiogram", null)
                        .WithMany()
                        .HasForeignKey("AntibiogramId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Models.Antibiotic", null)
                        .WithMany()
                        .HasForeignKey("MicsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AntibiogramAntibiotic1", b =>
                {
                    b.HasOne("Domain.Models.Antibiogram", null)
                        .WithMany()
                        .HasForeignKey("Antibiogram1Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Models.Antibiotic", null)
                        .WithMany()
                        .HasForeignKey("FirstPriorityMedicinesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AntibiogramAntibiotic2", b =>
                {
                    b.HasOne("Domain.Models.Antibiogram", null)
                        .WithMany()
                        .HasForeignKey("Antibiogram2Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Models.Antibiotic", null)
                        .WithMany()
                        .HasForeignKey("SecondPriorityMedicinesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AntibioticEmpiricTreatmentProtocol", b =>
                {
                    b.HasOne("Domain.Models.EmpiricTreatmentProtocol", null)
                        .WithMany()
                        .HasForeignKey("EmpiricTreatmentProtocolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Models.Antibiotic", null)
                        .WithMany()
                        .HasForeignKey("MedicinesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AntibioticPathogen", b =>
                {
                    b.HasOne("Domain.Models.Pathogen", null)
                        .WithMany()
                        .HasForeignKey("AntibioticSpectraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Models.Antibiotic", null)
                        .WithMany()
                        .HasForeignKey("MedicinesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CriterionEmpiricTreatmentProtocol", b =>
                {
                    b.HasOne("Domain.Models.EmpiricTreatmentProtocol", null)
                        .WithMany()
                        .HasForeignKey("EmpiricTreatmentProtocolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Models.Criterion", null)
                        .WithMany()
                        .HasForeignKey("OtherCriteriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Models.Antibiogram", b =>
                {
                    b.HasOne("Domain.Models.Pathogen", "Pathogen")
                        .WithMany()
                        .HasForeignKey("PathogenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pathogen");
                });

            modelBuilder.Entity("Domain.Models.Antibiotic", b =>
                {
                    b.HasOne("Domain.Models.AntibioticGroup", "AntibioticGroup")
                        .WithMany()
                        .HasForeignKey("AntibioticGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AntibioticGroup");
                });

            modelBuilder.Entity("Domain.Models.AntibioticGroup", b =>
                {
                    b.HasOne("Domain.Models.AntibioticGroup", "Parent")
                        .WithMany()
                        .HasForeignKey("ParentId");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("Domain.Models.Cause", b =>
                {
                    b.HasOne("Domain.Models.Disease", "Disease")
                        .WithMany("Causes")
                        .HasForeignKey("DiseaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Models.Pathogen", "Pathogen")
                        .WithMany()
                        .HasForeignKey("PathogenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Disease");

                    b.Navigation("Pathogen");
                });

            modelBuilder.Entity("Domain.Models.Dosage", b =>
                {
                    b.HasOne("Domain.Models.Antibiotic", "Antibiotic")
                        .WithMany("Dosages")
                        .HasForeignKey("AntibioticId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Domain.Models.Range", "GlomerularFiltrationRate", b1 =>
                        {
                            b1.Property<Guid>("DosageId");

                            b1.Property<bool>("IsMaxExclusive");

                            b1.Property<bool>("IsMinExclusive");

                            b1.Property<decimal>("Max");

                            b1.Property<decimal>("Min");

                            b1.Property<string>("Unit");

                            b1.HasKey("DosageId");

                            b1.ToTable("dosages");

                            b1
                                .ToJson("GlomerularFiltrationRate")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("DosageId");
                        });

                    b.Navigation("Antibiotic");

                    b.Navigation("GlomerularFiltrationRate")
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Models.EmpiricTreatmentProtocol", b =>
                {
                    b.HasOne("Domain.Models.Disease", "Disease")
                        .WithMany("EmpiricTreatmentProtocols")
                        .HasForeignKey("DiseaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Models.Pathogen", "SpecialInfection")
                        .WithMany()
                        .HasForeignKey("SpecialInfectionId");

                    b.Navigation("Disease");

                    b.Navigation("SpecialInfection");
                });

            modelBuilder.Entity("Domain.Models.IcuHospitalizeCriterion", b =>
                {
                    b.HasOne("Domain.Models.Criterion", "Criterion")
                        .WithMany()
                        .HasForeignKey("CriterionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Models.Disease", "Disease")
                        .WithMany("IcuHospitalizeCriteria")
                        .HasForeignKey("DiseaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Criterion");

                    b.Navigation("Disease");
                });

            modelBuilder.Entity("Domain.Models.ResistanceRiskFactor", b =>
                {
                    b.HasOne("Domain.Models.Criterion", "Criterion")
                        .WithMany()
                        .HasForeignKey("CriterionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Models.Disease", "Disease")
                        .WithMany("ResistanceRiskFactors")
                        .HasForeignKey("DiseaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Models.Pathogen", "Pathogen")
                        .WithMany()
                        .HasForeignKey("PathogenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Criterion");

                    b.Navigation("Disease");

                    b.Navigation("Pathogen");
                });

            modelBuilder.Entity("Domain.Models.NumericCriterion", b =>
                {
                    b.OwnsOne("Domain.Models.Range", "Value", b1 =>
                        {
                            b1.Property<Guid>("NumericCriterionId");

                            b1.Property<bool>("IsMaxExclusive");

                            b1.Property<bool>("IsMinExclusive");

                            b1.Property<decimal>("Max");

                            b1.Property<decimal>("Min");

                            b1.Property<string>("Unit");

                            b1.HasKey("NumericCriterionId");

                            b1.ToTable("criteria");

                            b1
                                .ToJson("Value")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("NumericCriterionId");
                        });

                    b.Navigation("Value")
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Models.Antibiotic", b =>
                {
                    b.Navigation("Dosages");
                });

            modelBuilder.Entity("Domain.Models.Disease", b =>
                {
                    b.Navigation("Causes");

                    b.Navigation("EmpiricTreatmentProtocols");

                    b.Navigation("IcuHospitalizeCriteria");

                    b.Navigation("ResistanceRiskFactors");
                });
#pragma warning restore 612, 618
        }
    }
}
