// <auto-generated />
using System;
using Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260808062259_InitPatientDb")]
    partial class InitPatientDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Models.Patient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("Admission")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("Discharge")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("HealthInsuranceCardNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsMale")
                        .HasColumnType("boolean");

                    b.Property<string>("MedicalRecordCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("FullName");

                    b.HasIndex("MedicalRecordCode");

                    b.ToTable("patients", (string)null);
                });

            modelBuilder.Entity("Domain.Models.Treatment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DoctorId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("type")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("character varying(21)");

                    b.HasKey("Id");

                    b.HasIndex("PatientId");

                    b.ToTable("treatments", (string)null);

                    b.HasDiscriminator<string>("type").HasValue("Treatment");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Domain.Models.EmpiricalTreatment", b =>
                {
                    b.HasBaseType("Domain.Models.Treatment");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TreatmentSite")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasDiscriminator().HasValue("empirical_treatment");
                });

            modelBuilder.Entity("Domain.Models.TargetedTreatment", b =>
                {
                    b.HasBaseType("Domain.Models.Treatment");

                    b.Property<string>("Pathogen")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasDiscriminator().HasValue("targeted_treatment");
                });

            modelBuilder.Entity("Domain.Models.Treatment", b =>
                {
                    b.HasOne("Domain.Models.Patient", "Patient")
                        .WithMany("Treatments")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsMany("Domain.Models.MedicineRecord", "MedicineRecords", b1 =>
                        {
                            b1.Property<Guid>("TreatmentId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd();

                            b1.Property<string>("Dose")
                                .IsRequired();

                            b1.Property<string>("Name")
                                .IsRequired();

                            b1.Property<string>("RouteOfAdministration")
                                .IsRequired();

                            b1.HasKey("TreatmentId", "__synthesizedOrdinal");

                            b1.ToTable("treatments");

                            b1
                                .ToJson("MedicineRecords")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("TreatmentId");
                        });

                    b.Navigation("MedicineRecords");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("Domain.Models.EmpiricalTreatment", b =>
                {
                    b.OwnsMany("Domain.Models.InfectionProbabilityRecord", "InfectionProbabilityRecords", b1 =>
                        {
                            b1.Property<Guid>("EmpiricalTreatmentId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd();

                            b1.Property<string>("Pathogen")
                                .IsRequired();

                            b1.Property<double>("Probability");

                            b1.HasKey("EmpiricalTreatmentId", "__synthesizedOrdinal");

                            b1.ToTable("treatments");

                            b1
                                .ToJson("InfectionProbabilityRecords")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("EmpiricalTreatmentId");
                        });

                    b.Navigation("InfectionProbabilityRecords");
                });

            modelBuilder.Entity("Domain.Models.Patient", b =>
                {
                    b.Navigation("Treatments");
                });
#pragma warning restore 612, 618
        }
    }
}
