// <auto-generated />
using System;
using Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260829092108_UpdateReasonToNullable")]
    partial class UpdateReasonToNullable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Models.Patient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("Admission")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("Discharge")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("HealthInsuranceCardNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsMale")
                        .HasColumnType("boolean");

                    b.Property<string>("MedicalRecordCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("FullName");

                    b.HasIndex("MedicalRecordCode");

                    b.ToTable("patients", (string)null);
                });

            modelBuilder.Entity("Domain.Models.Treatment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DoctorId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("type")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("character varying(21)");

                    b.HasKey("Id");

                    b.HasIndex("PatientId");

                    b.ToTable("treatments", (string)null);

                    b.HasDiscriminator<string>("type").HasValue("Treatment");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Domain.Models.EmpiricalTreatment", b =>
                {
                    b.HasBaseType("Domain.Models.Treatment");

                    b.HasDiscriminator().HasValue("empirical_treatment");
                });

            modelBuilder.Entity("Domain.Models.TargetedTreatment", b =>
                {
                    b.HasBaseType("Domain.Models.Treatment");

                    b.HasDiscriminator().HasValue("targeted_treatment");
                });

            modelBuilder.Entity("Domain.Models.Treatment", b =>
                {
                    b.HasOne("Domain.Models.Patient", "Patient")
                        .WithMany("Treatments")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("Domain.Models.EmpiricalTreatment", b =>
                {
                    b.OwnsOne("Domain.Models.EmpiricalDiagnosisRecord", "EmpiricalDiagnosisRecord", b1 =>
                        {
                            b1.Property<Guid>("EmpiricalTreatmentId");

                            b1.Property<decimal>("Crcl");

                            b1.Property<string>("ReasonForDifferentChoice");

                            b1.Property<string>("Severity")
                                .IsRequired();

                            b1.Property<string>("TreatmentSite")
                                .IsRequired();

                            b1.HasKey("EmpiricalTreatmentId");

                            b1.ToTable("treatments");

                            b1
                                .ToJson("EmpiricalDiagnosisRecord")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("EmpiricalTreatmentId");

                            b1.OwnsMany("Domain.Models.MedicineRecord", "DoctorChosenMedicines", b2 =>
                                {
                                    b2.Property<Guid>("EmpiricalDiagnosisRecordEmpiricalTreatmentId");

                                    b2.Property<int>("__synthesizedOrdinal")
                                        .ValueGeneratedOnAdd();

                                    b2.Property<string>("Classification")
                                        .IsRequired();

                                    b2.Property<string>("Dose")
                                        .IsRequired();

                                    b2.Property<Guid>("Id");

                                    b2.Property<string>("Name")
                                        .IsRequired();

                                    b2.Property<string>("RouteOfAdministration")
                                        .IsRequired();

                                    b2.HasKey("EmpiricalDiagnosisRecordEmpiricalTreatmentId", "__synthesizedOrdinal");

                                    b2.ToTable("treatments");

                                    b2.WithOwner()
                                        .HasForeignKey("EmpiricalDiagnosisRecordEmpiricalTreatmentId");
                                });

                            b1.OwnsMany("Domain.Models.MedicineRecord", "SystemRecommendedMedicines", b2 =>
                                {
                                    b2.Property<Guid>("EmpiricalDiagnosisRecordEmpiricalTreatmentId");

                                    b2.Property<int>("__synthesizedOrdinal")
                                        .ValueGeneratedOnAdd();

                                    b2.Property<string>("Classification")
                                        .IsRequired();

                                    b2.Property<string>("Dose")
                                        .IsRequired();

                                    b2.Property<Guid>("Id");

                                    b2.Property<string>("Name")
                                        .IsRequired();

                                    b2.Property<string>("RouteOfAdministration")
                                        .IsRequired();

                                    b2.HasKey("EmpiricalDiagnosisRecordEmpiricalTreatmentId", "__synthesizedOrdinal");

                                    b2.ToTable("treatments");

                                    b2.WithOwner()
                                        .HasForeignKey("EmpiricalDiagnosisRecordEmpiricalTreatmentId");
                                });

                            b1.OwnsMany("Domain.Models.InfectionProbabilityRecord", "InfectionProbabilityRecords", b2 =>
                                {
                                    b2.Property<Guid>("EmpiricalDiagnosisRecordEmpiricalTreatmentId");

                                    b2.Property<int>("__synthesizedOrdinal")
                                        .ValueGeneratedOnAdd();

                                    b2.Property<double>("Probability");

                                    b2.HasKey("EmpiricalDiagnosisRecordEmpiricalTreatmentId", "__synthesizedOrdinal");

                                    b2.ToTable("treatments");

                                    b2.WithOwner()
                                        .HasForeignKey("EmpiricalDiagnosisRecordEmpiricalTreatmentId");

                                    b2.OwnsOne("Domain.Models.PathogenRecord", "Pathogen", b3 =>
                                        {
                                            b3.Property<Guid>("InfectionProbabilityRecordEmpiricalDiagnosisRecordEmpiricalTreatmentId")
                                                .HasColumnName("InfectionProbabilityRecordEmpiricalDiagnosisRecordEmpiricalTre~");

                                            b3.Property<int>("InfectionProbabilityRecord__synthesizedOrdinal");

                                            b3.Property<Guid>("Id");

                                            b3.Property<string>("Name")
                                                .IsRequired();

                                            b3.HasKey("InfectionProbabilityRecordEmpiricalDiagnosisRecordEmpiricalTreatmentId", "InfectionProbabilityRecord__synthesizedOrdinal");

                                            b3.ToTable("treatments");

                                            b3.WithOwner()
                                                .HasForeignKey("InfectionProbabilityRecordEmpiricalDiagnosisRecordEmpiricalTreatmentId", "InfectionProbabilityRecord__synthesizedOrdinal");
                                        });

                                    b2.Navigation("Pathogen")
                                        .IsRequired();
                                });

                            b1.Navigation("DoctorChosenMedicines");

                            b1.Navigation("InfectionProbabilityRecords");

                            b1.Navigation("SystemRecommendedMedicines");
                        });

                    b.Navigation("EmpiricalDiagnosisRecord")
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Models.TargetedTreatment", b =>
                {
                    b.OwnsOne("Domain.Models.TargetedDiagnosisRecord", "TargetedDiagnosisRecord", b1 =>
                        {
                            b1.Property<Guid>("TargetedTreatmentId");

                            b1.Property<decimal>("Crcl");

                            b1.Property<string>("ReasonForDifferentChoice");

                            b1.HasKey("TargetedTreatmentId");

                            b1.ToTable("treatments");

                            b1
                                .ToJson("TargetedDiagnosisRecord")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("TargetedTreatmentId");

                            b1.OwnsMany("Domain.Models.MedicineRecord", "DoctorChosenMedicines", b2 =>
                                {
                                    b2.Property<Guid>("TargetedDiagnosisRecordTargetedTreatmentId");

                                    b2.Property<int>("__synthesizedOrdinal")
                                        .ValueGeneratedOnAdd();

                                    b2.Property<string>("Classification")
                                        .IsRequired();

                                    b2.Property<string>("Dose")
                                        .IsRequired();

                                    b2.Property<Guid>("Id");

                                    b2.Property<string>("Name")
                                        .IsRequired();

                                    b2.Property<string>("RouteOfAdministration")
                                        .IsRequired();

                                    b2.HasKey("TargetedDiagnosisRecordTargetedTreatmentId", "__synthesizedOrdinal");

                                    b2.ToTable("treatments");

                                    b2.WithOwner()
                                        .HasForeignKey("TargetedDiagnosisRecordTargetedTreatmentId");
                                });

                            b1.OwnsOne("Domain.Models.PathogenRecord", "Pathogen", b2 =>
                                {
                                    b2.Property<Guid>("TargetedDiagnosisRecordTargetedTreatmentId");

                                    b2.Property<Guid>("Id");

                                    b2.Property<string>("Name")
                                        .IsRequired();

                                    b2.HasKey("TargetedDiagnosisRecordTargetedTreatmentId");

                                    b2.ToTable("treatments");

                                    b2.WithOwner()
                                        .HasForeignKey("TargetedDiagnosisRecordTargetedTreatmentId");
                                });

                            b1.OwnsMany("Domain.Models.MedicineRecord", "SystemRecommendedMedicines", b2 =>
                                {
                                    b2.Property<Guid>("TargetedDiagnosisRecordTargetedTreatmentId");

                                    b2.Property<int>("__synthesizedOrdinal")
                                        .ValueGeneratedOnAdd();

                                    b2.Property<string>("Classification")
                                        .IsRequired();

                                    b2.Property<string>("Dose")
                                        .IsRequired();

                                    b2.Property<Guid>("Id");

                                    b2.Property<string>("Name")
                                        .IsRequired();

                                    b2.Property<string>("RouteOfAdministration")
                                        .IsRequired();

                                    b2.HasKey("TargetedDiagnosisRecordTargetedTreatmentId", "__synthesizedOrdinal");

                                    b2.ToTable("treatments");

                                    b2.WithOwner()
                                        .HasForeignKey("TargetedDiagnosisRecordTargetedTreatmentId");
                                });

                            b1.Navigation("DoctorChosenMedicines");

                            b1.Navigation("Pathogen")
                                .IsRequired();

                            b1.Navigation("SystemRecommendedMedicines");
                        });

                    b.Navigation("TargetedDiagnosisRecord")
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Models.Patient", b =>
                {
                    b.Navigation("Treatments");
                });
#pragma warning restore 612, 618
        }
    }
}
