<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
      <ProjectReference Include="..\Domain\Domain.csproj" />
      <ProjectReference Include="..\Application\Application.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="ZiggyCreatures.FusionCache" />
      <PackageReference Include="System.IdentityModel.Tokens.Jwt" />
      <PackageReference Include="BCrypt.Net-Next" />
      <PackageReference Include="MailKit" />
      <PackageReference Include="MimeKit" />
      <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" />
      <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
      <PackageReference Include="Microsoft.Extensions.Options" />
      <PackageReference Include="Aspire.Npgsql.EntityFrameworkCore.PostgreSQL" />
      <PackageReference Include="Microsoft.EntityFrameworkCore.Design" />
    </ItemGroup>

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

</Project>
